package Studentlogin.model;
// Generated May 30, 2022, 4:44:40 PM by Hibernate Tools 5.2.13.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Accounts generated by hbm2java
 */
@Entity
@Table(name = "accounts", catalog = "studentloginsystem")
public class Accounts implements java.io.Serializable {

	private String email;
	private Students students;
	private String pass;
	private byte[] avatar;
	private Integer incorrectCount;
	private Integer otp;
	private Date otpExpireTime;
	private Date lastLogin;
	private Date lastLogout;
	private Boolean activeStatus;
	private Date createdOn;
	private String createdBy;
	private Date updatedOn;
	private String updatedBy;

	public Accounts() {
	}

	public Accounts(Students students) {
		this.students = students;
	}

	public Accounts(Students students, String pass, byte[] avatar, Integer incorrectCount, Integer otp,
			Date otpExpireTime, Date lastLogin, Date lastLogout, Boolean activeStatus, Date createdOn, String createdBy,
			Date updatedOn, String updatedBy,String email) {
		this.students = students;
		this.pass = pass;
		this.avatar = avatar;
		this.incorrectCount = incorrectCount;
		this.otp = otp;
		this.otpExpireTime = otpExpireTime;
		this.lastLogin = lastLogin;
		this.lastLogout = lastLogout;
		this.activeStatus = activeStatus;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.email = email;
	}

	@GenericGenerator(name = "mod.AccountsIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "students"))
	@Id
	@GeneratedValue(generator = "mod.AccountsIdGenerator")

	@Column(name = "email", unique = true, nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "pass", length = 65535)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "avatar")
	public byte[] getAvatar() {
		return this.avatar;
	}

	public void setAvatar(byte[] avatar) {
		this.avatar = avatar;
	}

	@Column(name = "incorrect_count")
	public Integer getIncorrectCount() {
		return this.incorrectCount;
	}

	public void setIncorrectCount(Integer incorrectCount) {
		this.incorrectCount = incorrectCount;
	}

	@Column(name = "otp")
	public Integer getOtp() {
		return this.otp;
	}

	public void setOtp(Integer otp) {
		this.otp = otp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "otp_expire_time", length = 19)
	public Date getOtpExpireTime() {
		return this.otpExpireTime;
	}

	public void setOtpExpireTime(Date otpExpireTime) {
		this.otpExpireTime = otpExpireTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_logout", length = 19)
	public Date getLastLogout() {
		return this.lastLogout;
	}

	public void setLastLogout(Date lastLogout) {
		this.lastLogout = lastLogout;
	}

	@Column(name = "active_status")
	public Boolean getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(Boolean activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "created_by", length = 65535)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "updated_by", length = 65535)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
