package Studentlogin.model;

//default package
//Generated May 25, 2022, 12:36:26 AM by Hibernate Tools 5.2.13.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "students", catalog = "studentloginsystem")
public class Students implements java.io.Serializable {

	private String email;
	private String fullname;
	private String batch;
	private char gender;
	private Date dateOfBirth;
	private String program;
	private Date createdOn;
	private Date createdBy;
	private Date updatedOn;
	private Date updatedBy;
	private Accounts accounts;

	public Students() {
	}

	public Students(String email, String fullname, String batch, char gender, Date dateOfBirth) {
		this.email = email;
		this.fullname = fullname;
		this.batch = batch;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
	}

	public Students(String email, String fullname, String batch, char gender, Date dateOfBirth, String program,
			Date createdOn, Date createdBy, Date updatedOn, Date updatedBy) {
		this.email = email;
		this.fullname = fullname;
		this.batch = batch;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.program = program;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
	}

	@Id

	@Column(name = "email", unique = true, nullable = false, length = 320)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fullname", nullable = false, length = 65535)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "batch", nullable = false, length = 3)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "gender", nullable = false, length = 1)
	public char getGender() {
		return this.gender;
	}

	public void setGender(char gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", nullable = false, length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "program", length = 65535)
	public String getProgram() {
		return this.program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_by", length = 19)
	public Date getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Date createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_by", length = 19)
	public Date getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Date updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "students")
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

}
